[tool.poetry]
name = "extract-any-archive"
version = "0.1.0"
description = ""
authors = ["Martin Leitner-Ankerl <martin.ankerl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
